title: Steven Watterson
logo: /assets/img/Chol.png
description: Computational Cardiovascular Research @<a href="http://www.ulster.ac.uk/stratifiedmedicine"><i> Ulster University</i></a>
show_downloads: false
google_analytics: UA-43297847-1
theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
collections:
  - publications
  - press
  - newstuff
