title: Steven Watterson
logo: /assets/img/Chol.png
description: Computational Cardiovascular Research @<i> http://www.ulster.ac.uk/stratifiedmedicineThe University of Ulster</i>
show_downloads: false
google_analytics: UA-43297847-1
theme: jekyll-theme-minimal
